version: '3.8'

services:
  
  webapp:
    image: webapp_image
    container_name: c_webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:29090/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      
  api:
    image: api_image
    container_name: c_api
    build:
      context: .
      dockerfile: VacancyManagement.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:29090/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    
 
    

